# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cisco', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Windows Server Standard Edition', max_length=75)),
                ('version', models.CharField(help_text='2017', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(help_text='Microsoft', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='WebcastEncoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the stream type name', max_length=100)),
                ('description', models.CharField(help_text='Enter a short description', max_length=200)),
                ('ip_address', models.CharField(blank=True, help_text='ex. 192.168.0.1', max_length=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcast_platform.HardwareVendor')),
            ],
        ),
    ]
