# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Enter the channel name', max_length=10)),
                ('abbreviation', models.CharField(help_text='Enter the abbreviation here', max_length=10)),
                ('private', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('on-air', 'On Air'), ('off-air', 'Off Air')], default='on-air', max_length=10)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the lange name', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the phone bridge name', max_length=100)),
                ('phone_number', models.CharField(help_text='Enter the phone bridge number', max_length=30)),
                ('participant_pin', models.CharField(help_text='Enter the phone bridge participant access code', max_length=10)),
                ('host_pin', models.CharField(help_text='Enter the phone bridge host code', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Enter the stream name', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Enter a short description.', max_length=200, null=True)),
                ('uri', models.CharField(help_text="Enter the stream's uri", max_length=200)),
                ('alternate_uri', models.CharField(blank=True, help_text='enter the streams alternate uri.', max_length=200, null=True)),
                ('acl', models.CharField(blank=True, help_text='Enter the stream name', max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('stream_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Language')),
            ],
        ),
        migrations.CreateModel(
            name='StreamTokenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the token type name', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the stream type name', max_length=10)),
                ('description', models.CharField(help_text='Enter a short description', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.StreamType'),
        ),
        migrations.AddField(
            model_name='stream',
            name='token_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.StreamTokenType'),
        ),
        migrations.AddField(
            model_name='channel',
            name='phone_bridges',
            field=models.ManyToManyField(to='programs.PhoneBridge'),
        ),
        migrations.AddField(
            model_name='channel',
            name='streams',
            field=models.ManyToManyField(to='programs.Stream'),
        ),
    ]
