# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20171202_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='internal_only',
            field=models.BooleanField(default=False),
        ),
    ]
