# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_stream_internal_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebridge',
            name='label',
            field=models.CharField(default='test', help_text='Enter the phone bridge label', max_length=100),
            preserve_default=False,
        ),
    ]
