# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20171203_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='course_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='course_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='course_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='this_program_is_a_course',
            field=models.BooleanField(default=False),
        ),
    ]
