# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20171203_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_and_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.Channel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.Program')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
