# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_scheduledprogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledprogram',
            options={},
        ),
    ]
