# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20171204_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledprogram',
            name='start_date_and_time',
        ),
        migrations.AddField(
            model_name='scheduledprogram',
            name='start_date',
            field=models.DateField(default='2017-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledprogram',
            name='start_time',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
    ]
