# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20171204_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='course_abbreviation',
        ),
        migrations.RemoveField(
            model_name='program',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='course_number',
        ),
        migrations.AddField(
            model_name='program',
            name='associated_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Course'),
        ),
    ]
