# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20171204_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledprogram',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600), help_text='(minutes)'),
        ),
    ]
